url= 

###
GET http://127.0.0.1:5000 

###
GET http://127.0.0.1:5000/top100-list

###
GET http://127.0.0.1:5000/top100-history?days=30

###
GET http://127.0.0.1:5000/stock/ACB?days=30
###

GET http://127.0.0.1:5000/predict-top100?source=VNStock&limit=100&save_csv=true

###
GET http://127.0.0.1:5000/predict-top100-csv?limit=50&sort=true